spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team4
    username: team4
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret: dummy-jwt-secret # 실제 값으로 교체 필요
      expiration-time: 86400000 # 1 day in milliseconds
      token-prefix: Bearer
      header-string: Authorization
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-google-client-id # 실제 값으로 교체 필요
            client-secret: dummy-google-client-secret # 실제 값으로 교체 필요
            scope: email,profile,openid
          kakao:
            client-id: dummy-kakao-client-id # 실제 값으로 교체 필요
            client-secret: dummy-kakao-client-secret # 실제 값으로 교체 필요
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: dummy-redirect-uri # 실제 값으로 교체 필요
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao
          instagram:
            client-id: dummy-instagram-client-id # 실제 값으로 교체 필요
            client-secret: dummy-instagram-client-secret # 실제 값으로 교체 필요
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: dummy-redirect-uri # 실제 값으로 교체 필요
            scope: user_profile,user_media
            client-name: Instagram
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          instagram:
            authorization-uri: https://api.instagram.com/oauth/authorize
            token-uri: https://api.instagram.com/oauth/access_token
            user-info-uri: https://graph.instagram.com/me?fields=id,username,account_type
            user-name-attribute: id

server:
  port: 8080
